// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'
import { isServerEnvValid, getServerEnvErrors } from './env'

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    // Use VITE prefixed version if available (for server-side rendering), fallback to unprefixed
    const SUPABASE_ANON_KEY = process.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
      const missing: string[] = [];
      if (!SUPABASE_URL) missing.push('SUPABASE_URL');
      if (!SUPABASE_ANON_KEY) missing.push('VITE_SUPABASE_PUBLISHABLE_KEY or SUPABASE_PUBLISHABLE_KEY');
      
      const message = `[Supabase Auth Middleware] Missing environment variable(s): ${missing.join(', ')}`;
      console.error(message);
      
      throw new Error(
        'Authentication service is not properly configured. ' +
        'Please ensure Supabase environment variables are set.'
      );
    }
    
    const request = getRequest();

    if (!request?.headers) {
      console.error('[Supabase Auth Middleware] No request headers available');
      throw new Error('Unauthorized: Request validation failed');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Invalid authorization header format');
    }

    const token = authHeader.replace('Bearer ', '').trim();
    if (!token) {
      throw new Error('Unauthorized: Empty token provided');
    }

    try {
      const supabase = createClient<Database>(
        SUPABASE_URL,
        SUPABASE_ANON_KEY,
        {
          global: {
            headers: {
              Authorization: `Bearer ${token}`,
            },
          },
          auth: {
            storage: undefined,
            persistSession: false,
            autoRefreshToken: false,
          },
        }
      );

      const { data, error } = await supabase.auth.getClaims(token);
      if (error || !data?.claims) {
        console.warn('[Supabase Auth Middleware] Invalid token:', error?.message);
        throw new Error('Unauthorized: Token validation failed');
      }

      if (!data.claims.sub) {
        throw new Error('Unauthorized: No user ID found in token');
      }

      return next({
        context: {
          supabase,
          userId: data.claims.sub,
          claims: data.claims,
        },
      });
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      console.error('[Supabase Auth Middleware] Auth failed:', errorMessage);
      
      // Don't expose internal error details to client
      throw new Error('Unauthorized: Authentication failed');
    }
  },
);
