// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { envServer, isServerEnvValid, getServerEnvErrors, validateServerEnv } from './env';

function createSupabaseAdminClient() {
  // Validate server environment
  validateServerEnv();
  
  if (!isServerEnvValid()) {
    const errors = getServerEnvErrors();
    const message = `Missing Supabase server environment variable(s): ${errors.join(', ')}`;
    console.error(`[Supabase Admin] ${message}`);
    
    // Return a mock client that throws errors on use
    // This prevents server crash while still providing useful error messages
    return createMockAdminClient(message);
  }

  return createClient<Database>(
    envServer.supabaseUrl!,
    envServer.supabaseServiceRoleKey!,
    {
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      }
    }
  );
}

/**
 * Mock admin client that throws helpful errors when used
 * Prevents server crashes while providing feedback about missing env vars
 */
function createMockAdminClient(message: string) {
  const handler = {
    get() {
      throw new Error(
        `${message}. ` +
        'Supabase server is not configured. Server operations will fail.'
      );
    }
  };
  
  return new Proxy({}, handler) as any;
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
