// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { envClient, isClientEnvValid, getClientEnvErrors, validateClientEnv } from './env';

function createSupabaseClient() {
  // Validate environment variables
  validateClientEnv();
  
  if (!isClientEnvValid()) {
    const errors = getClientEnvErrors();
    const message = `Missing Supabase environment variable(s): ${errors.join(', ')}`;
    console.error(`[Supabase] ${message}`);
    
    // Return a mock client that throws errors on use
    // This prevents app crash while still providing useful error messages
    return createMockClient(message);
  }

  return createClient<Database>(
    envClient.supabaseUrl!,
    envClient.supabaseAnonKey!,
    {
      auth: {
        storage: typeof window !== 'undefined' ? localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      }
    }
  );
}

/**
 * Mock client that throws helpful errors when used
 * Prevents app crashes while providing feedback about missing env vars
 */
function createMockClient(message: string) {
  const handler = {
    get() {
      throw new Error(
        `${message}. ` +
        'Supabase is not configured. Please set up your environment variables.'
      );
    }
  };
  
  return new Proxy({}, handler) as any;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

